# 
# default: &default
#   adapter: postgresql
#   encoding: unicode
#   pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
#
# development:
#   <<: *default
#   database: ENV['RDS_DB_NAME']
#   username: ENV['RDS_USERNAME']
#   password: ENV['RDS_PASSWORD']
#   host: ENV['RDS_HOSTNAME']
#   port: ENV['RDS_PORTY']
#
# test:
#   <<: *default
#   database: zip_data_test
#
# production:
#   <<: *default
#   database: zip_data_production
#   username: zip_data
#   password: <%= ENV['ZIP_DATA_DATABASE_PASSWORD'] %>
#
default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: zip_data_development

test:
  <<: *default
  database: zip_data_test

production:
  <<: *default
  database: zip_data_production
  username: zip_data
  password: <%= ENV['ZIP_DATA_DATABASE_PASSWORD'] %>
